---
- name: Deploy Finance App
  hosts: webserver
  become: yes
  vars:
    project_dir: "/home/ec2-user/app"
    image_name: "finance-app-v2"
    container_name: "finance-app"

  tasks:
    - name: Pull latest code
      git:
        repo: "https://github.com/praveenkumarilla4git/InternalFinance-DocAnsi-GitHubActions_K8.git"
        dest: "{{ project_dir }}"
        version: main
        force: yes

    - name: Build Docker Image
      shell: "docker build -t {{ image_name }} ."
      args:
        chdir: "{{ project_dir }}"

    - name: Force Cleanup existing container
      # Using a multi-line shell block ensures both commands are attempted
      shell: |
        docker stop {{ container_name }} || true
        docker rm {{ container_name }} || true
      ignore_errors: yes

    - name: Run New Docker Container
      shell: "docker run -d --name {{ container_name }} -p 5000:5000 {{ image_name }}"
      args:
        chdir: "{{ project_dir }}"