- name: Deploy Finance App
  hosts: webserver
  become: yes
  vars:
    project_dir: "/home/ec2-user/app"
    image_name: "finance-app-v2"
    container_name: "finance-app" # Crucial for cleanup

  tasks:
    - name: Pull latest code
      git:
        repo: "https://github.com/praveenkumarilla4git/InternalFinance-DocAnsi-GitHubActions_K8.git"
        dest: "{{ project_dir }}"
        version: main
        force: yes

    - name: Cleanup existing container
      shell: "docker stop {{ container_name }} && docker rm {{ container_name }} || true"

    - name: Build and Run
      shell: |
        docker build -t {{ image_name }} .
        docker run -d --name {{ container_name }} -p 5000:5000 {{ image_name }}
      args:
        chdir: "{{ project_dir }}"